from .pixel_snapping import NODE_CLASS_MAPPINGS as PS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PS_DISPLAY_MAPPINGS
from .mask_crop import NODE_CLASS_MAPPINGS as MC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MC_DISPLAY_MAPPINGS
from .mask_restore import NODE_CLASS_MAPPINGS as MR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MR_DISPLAY_MAPPINGS

# 合并所有节点
NODE_CLASS_MAPPINGS = {**PS_MAPPINGS, **MC_MAPPINGS, **MR_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**PS_DISPLAY_MAPPINGS, **MC_DISPLAY_MAPPINGS, **MR_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
